### ISSUE TITLE
Pagination component disables "first page of results" button when on second page

### ISSUE THREAD

**Issue by bporterfield** [looker-open-source/components#1775]
https://components.looker.com/components/actions/pagination 

It does however enable the button once on third page of results.

**Comment by lukelooker** [comment]
Hey @jhardy - Looking at the code for this it appears the choice to disable the "first page of results" button was intentional but wanted to verify if that was in fact the design intent.

I believe the logic was that we didn't want two buttons pointing to the same page for accessibility?

**Comment by bporterfield** [comment]
If it's helpful, my experience was "I just wanna go back to the start of this data" without knowing where I was in the pages (I happened to be on the 2nd page). The fact that the "go back to the start" button was disabled made me feel like there was something broken.

**Comment by jhardy** [comment]
@lukelooker I honestly cant remember why that choice was made, but after playing with it a bit, it does feel like the wrong choice. I can't think of any accessibility or UX reason on why we would want to disable it until the third page of the results and the same thing goes for being a the end of the result set. 

My vote would be to enable those buttons as long as you are not on the first or last set of results.

**Comment by bporterfield** [comment]
👍 would love that!

**Comment by lukelooker** [comment]
Fixed in `main` - we'll be releasing a new version with the fix in the next 24 hours :)
