### ISSUE TITLE
Docs example not functional

### ISSUE THREAD

**Issue by bporterfield** [looker-open-source/components#1779]
https://components.looker.com/components/dialogs/drawer

Second example, `useDrawer`, clicking the button does nothing for me

**Comment by bporterfield** [comment]
Also worth noting: At the top of this component doc is this:

> NOTE: Currently Drawer only supports attachement to the right side of the viewport. Support for additional placement options is planned in the future.

At the bottom is this note: 

> Determines how surface is positioned in the the viewport.
> 
> right (default) - surface is centered horizontally and vertically above mobile breakpoint.
> mobile: positioned at top of window and covers entire width.
> width: defaults to 100% in mobile breakpoint and 37.5rem above that unless otherwise specified
> height: fits content unless it's explicitly specified with minHeight prop
> left - positioned to cover nearly the entire window.
> mobile & tablet: cover the entire window.

These two things appear to be in conflict? Also, attachment is misspelled in first note.

**Comment by lukelooker** [comment]
This was resolved in latest version of documentation. We're currently working with Ops team to get DNS redirected to new publishing location at https://looker-open-source.github.io/components/latest/components/dialogs/drawer
