### ISSUE TITLE
home page link to Develop not working

### ISSUE THREAD

**Issue by DucarrougeR** [looker-open-source/components#1870]
Quick issue on the Home page.
When opening https://looker-open-source.github.io/components/latest/

there is an item in the center left:
>Install
>Visit the [Develop](https://looker-open-source.github.io/develop/) page for instructions on installing @looker/components

However that link to Develop does not work.

It links to `https://looker-open-source.github.io/develop/`
but should link to `https://looker-open-source.github.io/components/latest/develop/`

Link to code: https://github.com/looker-open-source/components/blob/main/www/src/pages/index.tsx#L100

**Comment by lukelooker** [comment]
Thanks for the head's up @DucarrougeR - the site just got re-deployed with the fix for that!
