### ISSUE TITLE
New design of Tabs2

### ISSUE THREAD

**Issue by kufelkamil** [looker-open-source/components#2927]
Hello,

Is there any way to remove the rectangle background for focused and hovered Tabs2 introduced recently? 
Everything in @looker/components has rounded corners and usually also solid border.
I would prefer playing with the bottom border color for hover/focus effects, as it was before. 
Currently Tabs2 component looks like something under development, as it stands out from the appearance of other components. 

<img width="1429" alt="obraz" src="https://user-images.githubusercontent.com/9267248/147819541-0aac2f35-9d6b-4844-9226-f95c277dd3fe.png">

https://codesandbox.io/s/friendly-http-eg41o?file=/src/index.tsx

**Comment by mdodgelooker** [comment]
Hi @kufelkamil thank you for asking. We do not offer a way to turn off the background color on hover & focus. The recent updates are to align with the Google Material 2 implementation of tabs: https://boq-experimental.sandbox.google.com/materialwiz/tabs
