### ISSUE TITLE
Duplicated tooltip for titleIcon in DataTable

### ISSUE THREAD

**Issue by kufelkamil** [looker-open-source/components#2928]
Hello,

When `titleIcon` prop is used to replace title with icon in `DataTable`, when icon is hovered both system and custom tooltip are rendered. The bug occurs in Safari, Firefox and Chrome. 

<img width="1420" alt="obraz" src="https://user-images.githubusercontent.com/9267248/148042360-0b78bf65-180c-47f3-8bb2-e15e92475f8c.png">

https://codesandbox.io/s/unruffled-bose-5k3km?file=/src/index.tsx

**Comment by mdodgelooker** [comment]
Thank you @kufelkamil for raising this issue. We are working on a fix.

**Comment by mdodgelooker** [comment]
Hi @kufelkamil this issue is fixed in v2.8.14 https://codesandbox.io/s/bold-noyce-r2fxu
