### ISSUE TITLE
Select component inside Dialog loses focus after changing value

### ISSUE THREAD

**Issue by kufelkamil** [looker-open-source/components#2953]
Hi, 

We utilize `Dialog` component to create many kinds of forms in Looker, however we struggle with the weird behaviour of the `Select` component when used inside `Dialog` - every time the value of `Select` is changed, the component loses focus and the first form field in the `Dialog` gets it. Apart of this being confusing it also trigger scrolling to the top if dialong content is long. Is is possible to somehow disable this behaviour?  

https://codesandbox.io/s/xenodochial-colden-t6zb7n?file=/src/index.tsx

**Comment by treshugart** [comment]
Hey, @kufelkamil. Thanks for the report and reproduction. We'll look into it soon and update the issue as we do.

**Comment by swhitey** [comment]
Hey there @kufelkamil, it seems like the behavior you described isnt happening for me in your codesandbox example and I'm unable reproduce the issue using other methods.  Let me know if I'm misunderstanding something or you can provide another reproduction for us to continue to troubleshoot. Thanks

**Comment by kufelkamil** [comment]
Hi @swhitey, I still see the issue. Please find the gif of the codesandbox recording attached. 

Maybe this is a browser-related issue, I have checked it in Firefox.

![Nagranie z ekranu 2022-05-10 o 13 45 39](https://user-images.githubusercontent.com/9267248/167621589-d29ce35b-5074-45e2-a69d-193880d9e614.gif)

**Comment by mdodgelooker** [comment]
@kufelkamil are you using Firefox? So far that's the only browser I've been able to reproduce this in.

**Comment by guyellis** [comment]
We have an internal ticket `229857707` that fixed this and another `246786486` to get this published.

**Comment by mdodgelooker** [comment]
@kufelkamil this is fixed in `@looker/components` version `4.9.3` just published.
