### ISSUE TITLE
React version as a dependency

### ISSUE THREAD

**Issue by kajyr** [looker-open-source/components#2963]
Hi,

we would like to utilize this library to implement our interface for looker dashboards, but I see that the published npm package requires a peer dependency with `react@"^16.11"`, and to make things worse in the main branch of the repo, in package.json react 16 is set as a `dependency`.

Since this will cause 2 react versions in the dependency tree, would it be possible to make this UI library independent of the installed react version?

**Comment by guyellis** [comment]
No date on fixing this yet but we do have an internal ticket # 244340534 that is looking at this.

**Comment by mdodgelooker** [comment]
The latest versions of all packages widen the React peer dependency range up to version 18.
