### ISSUE TITLE
Apply components to Looker custom viz explore UI

### ISSUE THREAD

**Issue by zmeers** [looker-open-source/components#2965]
Hello!

I'm looking to build some custom visualizations in Looker. I would like to apply components to organize chart options as the current set up is pretty limiting (see this old issue in the custom_visualizations repo: https://github.com/looker/custom_visualizations_v2/issues/130)  compared to the standard UI for native Looker charts. However -- and this may because I'm more of a data scientist than a FE SWE -- it's unclear to me whether components can be applied to custom visualizations in a Looker project or if they are only meant for external applications? If someone can advise, that would be fantastic. 

Thanks!
Zoe

**Comment by dbchristopher** [comment]
Hi @zmeers,
We don't have anything out of the box in Looker Components that would add more flexible options and layouts for custom visualizations. That being said, I don't think there is anything that would prevent you from using Looker Components in a custom vis bundle. Do you have a mockup of what you're trying to accomplish?

**Comment by zmeers** [comment]
Thanks @dbchristopher. I have a menu of expandable toggles in the edit panel. I'm looking to override the boolean toggles with an accordian menu. It seems like this would be possible with the [tree component](https://looker-open-source.github.io/components/latest/components/content/tree). It's not a must-have for me, but I was just wondering if there happened to be an easy way to switch out the toggles for a tree or accordion layout. 

<img width="228" alt="Screen Shot 2022-07-08 at 11 02 26 am" src="https://user-images.githubusercontent.com/26280637/177895717-2a154682-87ee-4a0c-bb10-b89599477e09.png">
