### ISSUE TITLE
4.0.3 available on npm but not on GitHub

### ISSUE THREAD

**Issue by kufelkamil** [looker-open-source/components#2973]
Hello, is there a reason for not publishing new versions of Looker Components here on GitHub? 
Where can I find a changelog for 4.0.3? The last update in the repo was five months ago.

**Comment by guyellis** [comment]
For internal folk looking at this issue our tracking number is `245966799`.

@kufelkamil as per the above number we have a ticket tracking this issue but we don't have a timeline on this yet.

As a temporary workaround you can create an empty folder on your system and do:

```
npm i @looker/components
```

and then look at the `node_modules/@looker/components/CHANGELOD.md` file which will have the details that you are looking for.

**Comment by guyellis** [comment]
@kufelkamil also just [published the release tag](https://github.com/looker-open-source/components/releases/tag/%40looker%2Fcomponents%403.0.1) and now trying to solve whey the date on that is not reflecting today.

**Comment by mdodgelooker** [comment]
As of `4.0.4` the source is now up-to-date in this repository.

https://github.com/looker-open-source/components/blob/main/packages/components/CHANGELOG.md
