### ISSUE TITLE
Filter cascading doesn't work 

### ISSUE THREAD

**Issue by polkadots007** [looker-open-source/components#2974]
I am using using the `FilterCollection` and `DashboardFilter` to implement filter cascading.

Already having selected some values in multiple filters, if I select and deselect a value in one of the cascaded filter(with no selections made) and run `.updateFilters` function of embedded dashboard then the cascaded filter shows all values instead of only the cascaded values i.e. cascading disappears.

I can see the `updateFilters` is taking an empty object.
Can you please explain why this happens?

**Comment by mdodgelooker** [comment]
Hi @polkadots007 we've created an internal ticket to track this issue with an id of 257994281.

**Comment by mdodgelooker** [comment]
Hi @polkadots007 can you provide a bit more detail on this issue? Either a screen capture or a code snippet that includes the components and embedded dashboard – or preferably both. If you'd prefer to go through customer support rather than posting here, that's no problem, they'll know how to find me. :)

**Comment by polkadots007** [comment]
I can explain the flow a bit. Hope that helps. The implementation is as follows. 

`<FilterCollection>
{filterSet.map((item: any)=>{
<DashboardFilter
    key={item.id}
    filter={item}
    sdk={sdk}
     expression={filterValues
current[item.name] ? filterValues.current [item.name]: ' '}
   onChange= {(value: any)=>handleChange(value)}
})
<FilterCollection>`

Inside `handleChange` function, 
I take the value and set it to `filterValues` object and set the values inside another global object `createSelectionObj` in format of `{ filtername : value}`

Then after that when I click on a submit button, the button takes the `createSelectionObj` and calls `dashboard.updateFilters(createSelectionObj)` and `dashboard.run()`

**Comment by polkadots007** [comment]
Thanks for the suggestion. I would contact customer support!
