### ISSUE TITLE
React 18+ Providers error when FC is using children

### ISSUE THREAD

**Issue by taystack** [looker-open-source/components#2975]
|package|version|
|---|---|
|`typescript`| `4.9.4`|
|`react`| `18.2.0`|
|`@looker/components`| `4.0.4`|

I am getting a typescript error when using the `<ComponentsProvider>`:
```bash
Type '{ children: Element }' has no properties in common with type 'IntrinsicAttributes & ComponentsProviderProps'
```

See here:
![Screen Shot 2023-01-05 at 11 57 18 AM](https://user-images.githubusercontent.com/2994672/210868941-73810762-49d9-45b2-8fab-58cf364ab984.png)

Fix:
I personally ran into this problem when upgrading to react 18. `FC` properties no longer expect `children`, so custom properties need to be more explicit:
```typescript
export interface ComponentsProviderProps extends ThemeProviderProps, ExtendComponentsTheme, UseI18nProps {
  // ...
}

// Should extend an additional React.PropsWithChildren<{}> type:
export interface ComponentsProviderProps extends ThemeProviderProps, ExtendComponentsTheme, UseI18nProps, React.PropsWithChidlren<{}> {
  // ...
}
```

I can make a PR for this if that helps.

**Comment by taystack** [comment]
I made a PR https://github.com/looker-open-source/components/pull/2976

Hopefully this change doesn't break anything - it shouldn't but I had troubles with development.

- It looks like the project follows the workspaces pattern, but there isn't a root `package.json` for linking the packages together. It's not clear how to install the dependencies for any one package.
- Where is `@looker/babel-*` stuff and how do I resolve it when I `npm install` from `components/packages/components-providers`?

Thanks ya'll.

**Comment by elliot-at-looker** [comment]
This is being tracked internally with ticket 255844186

**Comment by guyellis** [comment]
@taystack we are actively working on a change to address this in our internal code base. Once complete we'll release a fix. Thanks.

**Comment by mdodgelooker** [comment]
@taystack this issue is resolved in `v4.1.1`.

**Comment by guyellis** [comment]
@taystack did this resolve your issue?

**Comment by taystack** [comment]
@guyellis, @mdodgelooker I've verified this works on React18 without any typescript issues. 🌮 thanks for this!
