### ISSUE TITLE
DashboardFilter Component isn't automatically encoding the special character in filter values

### ISSUE THREAD

**Issue by polkadots007** [looker-open-source/components#2977]
The DashboardFilter Component is not recognizing the filter values from suggestions having special characters such as '&' or '+'.
For Example:

If value selected is 'A&B Area Ltd+P Co',
then in network console, under `suggestions?term=&filters=` it is shows that payload is passed as 
**filters:** {"view_name.example_filter":"\\"A
**B Area Ltd P Co\\""}:**

The filter cascading fails as well as a result and filters are not passed properly to dashboard as well.

**Comment by guyellis** [comment]
Our internal tracking number for this is `267303329`

**Comment by mdodgelooker** [comment]
Hi @polkadots007 this issue is fixed in @looker/filter-components@1.0.3.
