### ISSUE TITLE
Typescript errors using Menu component.

### ISSUE THREAD

**Issue by taystack** [looker-open-source/components#2978]
|package|version|
|---|---|
|`@looker/components`| `4.1.3`|
|`typescript`|`4.9.4`|
|`react`|`18.0.0`|

It appears every single possible `Menu` and `Popover` property is now required. Ironically, some properties are mutually exclusive (ie: `children` and `dangerouslySetInnerHTML`). The current workaround is to add `@ts-expect-error` before using `Menu`.

![Screenshot 2023-03-27 at 10 26 52 AM](https://user-images.githubusercontent.com/2994672/228019323-77c83b78-5329-4e7b-a11b-15bef5041cd1.png)

**Comment by guyellis** [comment]
Our internal tracking number on this is `275437827`.

**Comment by mdodgelooker** [comment]
Hi @taystack would you be able to provide the dependencies and devDependencies for a minimum repro? I'm not able to repro the issue with the following:

```

  "dependencies": {
    "@looker/components": "4.1.3",
    "lodash": "^4.17.21",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.6"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.11",
    "@types/styled-components": "^5.1.26",
    "@types/styled-system": "^5.1.16",
    "typescript": "^4.9.4",
    "web-vitals": "^2.1.4"
  },
  ```

**Comment by mdodgelooker** [comment]
@taystack I'm also curious what version is in your `node_modules/@types/react/package.json`. Thanks!

**Comment by mdodgelooker** [comment]
Thank you so much for the repro @taystack! Adding `"@types/styled-system": "^5.1.16",` to your `devDependencies` should solve the issue. We'll work on improving this in our documentation.
