### ISSUE TITLE
Broken dependency on @looker/visualizations@1.1.4

### ISSUE THREAD

**Issue by williamtsoi1** [looker-open-source/components#2979]
`@looker/visualizations@1.1.4` depends on `@looker/visualizations-visx@1.0.3` which is not released on npmjs

**Comment by guyellis** [comment]
Tracking internally with `275470100`

**Comment by mdodgelooker** [comment]
Hi @williamtsoi1, @looker/visualizations-visx@1.0.3 is now published.
