### ISSUE TITLE
All the documentation links in components/packages/visualizations are 404s

### ISSUE THREAD

**Issue by kevin-wallace-wpro** [looker-open-source/components#2981]
ie from https://github.com/looker-open-source/components/blob/ec11d41fec6a79d8095b19b3213c5d3339a17965/packages/visualizations/README.md

current text with the 404 links..

API: https://cloud.google.com/looker/docs/reference/api-and-integration/api-getting-started
Looker extension framework: https://cloud.google.com/looker/docs/data-modeling/extension-framework/extension-framework-intro
standard charts: https://cloud.google.com/looker/docs/exploring-data/visualizing-query-results/visualization-types
Looker Visualization Components documentation: https://cloud.google.com/looker/docs/data-modeling/extension-framework/vis-components

Thank you

**Comment by kenvlooker** [comment]
Updates submitted via CL https://critique.corp.google.com/cl/527091327. The URLs above should redirect to the correct pages.
